<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class AppController extends Controller
{

    public function beforeAction($action)
    {
        $lang = $_COOKIE['til'];
        if ($lang == '') $lang = 'eng';
        Yii::$app->language = $lang;

        if (explode('.', preg_replace('#^https?://#', '', Yii::$app->getRequest()->getHostInfo()))[0] == 'seller')
            $this->redirect('/admin');
        $this->view->title = \Yii::$app->name;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    protected function setMeta($title = null, $keywords = null, $description = null)
    {
        $this->view->title = $title;
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => "$keywords"]);
        $this->view->registerMetaTag(['name' => 'description', 'content' => "$description"]);
    }

}
