<?php

namespace app\module\admin\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property int $parent_id
 * @property string $title
 * @property string|null $description
 * @property string|null $keywords
 * @property string|null $img
 * @property string|null $baner_img
 */
class Category extends \yii\db\ActiveRecord
{
    public $file;
    public $b_img;
    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'parent_id']);
    }

    public function getProduct() {
        return $this->hasMany(Product::class, ['category_id' => 'id']);
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['parent_id'], 'integer'],
            [['title'], 'required'],
            [['title', 'description', 'keywords'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => 'Parent category',
            'title' => 'Title',
            'description' => 'Description',
            'keywords' => 'Keywords',
        ];
    }

    public function beforeSave($insert)
    {
        if($file = UploadedFile::getInstance($this, 'file')){
            $file = UploadedFile::getInstance($this, 'file');
            if (!is_dir('upload/'.Yii::$app->user->identity->username)) {
                mkdir('upload/'.Yii::$app->user->identity->username);
            }
            $dir = 'upload/'.Yii::$app->user->identity->username .'/'. date("Y-m-d") . '/';
            if(!is_dir($dir)){
                mkdir($dir);
            }
            $file_name = uniqid() . '_' . $file->baseName . '.' . $file->extension;
            $this->img = $dir . $file_name;
            $file->saveAs($this->img);
            $this->img = '/'.$dir . $file_name;
        }

        if($b_img = UploadedFile::getInstance($this, 'b_img')){
            $b_img = UploadedFile::getInstance($this, 'b_img');
            if (!is_dir('upload/'.Yii::$app->user->identity->username)) {
                mkdir('upload/'.Yii::$app->user->identity->username);
            }
            $dir = 'upload/'.Yii::$app->user->identity->username .'/'. date("Y-m-d") . '/';
            if(!is_dir($dir)){
                mkdir($dir);
            }
            $file_name = uniqid() . '_' . $b_img->baseName . '.' . $b_img->extension;
            $this->baner_img = $dir . $file_name;
            $b_img->saveAs($this->baner_img);
            $this->baner_img = '/'.$dir . $file_name;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
